### ISSUE TITLE
Outlook 2007 | 2010 bad display

### ISSUE THREAD

**Issue by etiks3** [leemunroe/htmlemail#9]
Hi there,

I'm using your templates, but it's not working properly in Outlook 2007 and outlook 2010.
Is there a trick to workaround it?
Thanks for your prompt reply.

Sylvain

**Comment by leemunroe** [comment]
@etiks3 Hey Sylvain, sorry to hear that. Can you email me hello@htmlemail.io with the following and I'll try to figure out what the issue is:

1. More details about what is not behaving as expected
2. The code you're sending (you can use http://codeshare.io to privately share your code)
3. A screenshot of what you're seeing in Outlook 2007 and 2010

Thanks

**Comment by leemunroe** [comment]
Closing as resolved over email. Thanks @etiks3
